### ISSUE TITLE
Multiple Evohome wiki. Version number not being added to manifest.json - prevents starting

### ISSUE THREAD

**Issue by LampyDave** [zxdavb/evohome-async#10]
Hi there,
Apologies if I'm doing this wrong - I'm brand new to HA. Very many thanks for the idiot-proof guide to getting this working.
I followed this process for the first time a few days ago, and just followed it again after the recent Core update. On both occasions the version number was not added to the manifest.json file and that subsequently prevented the integration from starting.

Screenshot attached below showing the part of the process. I have not yet found an idiot-proof guide to sed to allow me to un-pick why this might be. When I amend the file manually the integration will then start fine.

Thanks again for making this accessible to massive amateurs like me :)

![ACDSeeQVUltimate13_cP86a4ymjF](https://github.com/zxdavb/evohome-async/assets/42514569/5e61dc39-6a26-47e0-adb8-52e69e1d3f1b)

**Comment by zxdavb** [comment]
I have updated the wiki with a working **sed** command: `sed -i '/{/a \ \ "version": "0.0.1",' manifest.json`

I have addressed some other issues with the wiki.

Thanks for helping!
