### ISSUE TITLE
Does wiki still apply for multiple locatons in HA 2024.7

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [zxdavb/evohome-async#21]
@zxdavb I did see that in HA 2024.7 the const.py file is changed so I was wondering does the WIKI for multiple locations still applies and works and how should this file now look, because in WIKI still is showing the old file when putting command to check if changes where applied to files.

I am referring to step 4 and 5 of the WIKI

https://github.com/zxdavb/evohome-async/wiki/Hass:-Multiple-Evohome-Locations

EDIT 
![Screenshot_20240704_214752_Chrome](https://github.com/zxdavb/evohome-async/assets/97987488/9923e58d-5c1c-4a2d-a3c7-dd18b2c56522)

I assume now  Domain: Final" should be evohome_1?

**Comment by smarthomefamilyverrips** [comment]
@zxdavb could you please respond when you have time

**Comment by smarthomefamilyverrips** [comment]
Is there anyone that could help me out with this question?

**Comment by smarthomefamilyverrips** [comment]
@zxdavb I would highly appreciate if you could supply me with a answer as I am waiting to update to HA 2024.7.x because I not want to break my second instance of the evohome integration because is pretty vital for me to have it available. Thanks Upfront!

**Comment by smarthomefamilyverrips** [comment]
> Yes it's still the same. the `Final` is a python qualifier and doesn't effect this guide.

So the line  Domain: Final = "evohome" should he changed into Domain: Final = "evohome_1" ?

**Comment by bmhughes** [comment]
Yes

**Comment by zxdavb** [comment]
The wiki has been updated. 

@smarthomefamilyverrips In future, please ask your questions in the HA community forum, as I have advised before.

I am unsubscribing from this thread - people should accept I have no obligation to provide them with individual support to satisfy their 'vital' needs.

**Comment by smarthomefamilyverrips** [comment]
> The wiki has been updated.
> 
> @smarthomefamilyverrips In future, please ask your questions in the HA community forum, as I have advised before.
> 
> I am unsubscribing from this thread - people should accept I have no obligation to provide them with individual support to satisfy their 'vital' needs.

@zxdavb first of all thanks for updating the wiki!

Secondly you told yourself here is the correct location to ask questions as you can see in the screenshot. 

![Screenshot_20240718_160646_Chrome](https://github.com/user-attachments/assets/2d7864ad-e209-44d4-a14c-54fb1fdaf98f)

Thirdly I not understand your "hostile" reaction I think I asked polite if you or someone else could help me, nowhere I stated that you are obligated to answer or help, but if you are code owner for the evohome integration and are the one that wrote the WIKI how to use multiple evohome integrations I think is normal people will also turn to you when they have questions or issue's. I understand it is all on voluntary base and am sure we all appreciate the work and time all of you code owners put into it, so honestly I not really understand your reaction as you said nobody obligated you to get involved doing this but if you get involved you should expect that people ask you questions or help.

Anyway thanks for your efforts and help.
