### ISSUE TITLE
ssl cert for tccna.honeywell.com is only valid for tccna.resideo.com

### ISSUE THREAD

**Issue by cathelijne** [zxdavb/evohome-async#32]
I am using the evohome-async package from the evohome homeassistant integration.

Since yesterday (?) I see a lot of ssl errors in my logs: 

`[2024-12-12 13:45:43.385 WARNING (MainThread) [homeassistant.components.evohome] Unable to obtain the latest high-precision temperatures. Check your network and the vendor's service status page. Proceeding without high-precision temperatures for now. Message is: Cannot connect to host tccna.honeywell.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'tccna.honeywell.com'. (_ssl.c:1020)")]` (among others)

and the integration no longer works. 

I looked up the certificate for tccna.honeywell.com, and it's not valid for that hostname, but it _is_ valid for tccna.resideo.com.
```
☁  ~  seecert tccna.honeywell.com
Server:		100.100.100.100
Address:	100.100.100.100#53

Non-authoritative answer:
Name:	tccna.honeywell.com
Address: 20.62.73.190

Connecting to 20.62.73.190
depth=2 C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert High Assurance EV Root CA
verify return:1
depth=1 C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 C=US, ST=Arizona, L=Scottsdale, O=Resideo Technologies, Inc., CN=TCCNA.resideo.com
verify return:1
DONE
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0c:90:b5:65:10:e4:a7:be:d3:52:c8:5b:e8:ba:ba:b0
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert SHA2 High Assurance Server CA
        Validity
            Not Before: Nov 20 00:00:00 2024 GMT
            Not After : Dec 21 23:59:59 2025 GMT
        Subject: C=US, ST=Arizona, L=Scottsdale, O=Resideo Technologies, Inc., CN=TCCNA.resideo.com
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:TCCNA.resideo.com, DNS:TCCEU.resideo.com, DNS:TCCAP.resideo.com, DNS:TCCNAS.resideo.com, DNS:TCCEUS.resideo.com, DNS:TCCAPS.resideo.com
```
(snipped some irrelevant parts from output for readability)

Weirdly enough, the two hosts don't share their IP-address:
```
☁  ~  host tccna.honeywell.com
tccna.honeywell.com has address 20.62.73.190
tccna.honeywell.com mail is handled by 10 m01.honeywell.com.
☁  ~  host tccna.resideo.com
tccna.resideo.com has address 135.224.164.118
☁  ~
```

The hostname is hardcoded in `evohomeasync2/const.py` and in `evohomeasync/broker.py`.

If I change the hostname from `tccna.honeywell.com` to `tccna.resideo.com` _directly in the homeassistant container_ in those files (found at `/usr/local/lib/python3.13/site-packages/evohomeasync2/const.py` and in `/usr/local/lib/python3.13/site-packages/evohomeasync/broker.py` in 2024.12) and restart homeassistant, the integration works.
(As an aside, I was surprised the change survived a container restart, but that's a whole different story)

I am more than happy to raise this with Resideo customer service myself of course. But someone might find this hacky stopgap useful while Resideo fix their certs.

(edited to clarify you have to update both evohome-async and evohome-async2 packages)

edit2: I had not foreseen this would gain so much traction in just an hour :) 
For all of you coming here and wondering how to apply the stopgap: if you want to change the files, you have to do it in the running container. This means first getting access to the host that runs the docker daemon (i.e. the machine that runs HAOS), en then exec into the container. AFAIK, using the standard ssh integration from inside homeassistant _does not work_, you really have to log on to the OS that runs the docker daemon.

@leen67 posted a step by step in the HA Core issue that also deals with this: https://github.com/home-assistant/core/issues/132366#issuecomment-2539283798

**Comment by ippo112** [comment]
same issue for me, certification problem with HA integration. 
The mobile App works fine, the web site (https://international.mytotalconnectcomfort.com/) doesn't work.

**Comment by cedcabgit** [comment]
> can someone point me in the direction of how i get to those files ? i cant see the /usr folder in my file editor ?

I struggled a bit as well. Go in your container and launch a terminal from there. then you can navigate in your directories

**Comment by bigstevehardy** [comment]
i can go into terminal but those folders dont exist ? i have usr etc ... but no python ?

**Comment by bigstevehardy** [comment]
![image](https://github.com/user-attachments/assets/657a6384-bc4a-46a9-80fa-af3ba550e450)

**Comment by bigstevehardy** [comment]
this is using terminal inside of home assistant (from the sidebar)

**Comment by bigstevehardy** [comment]
Will SSH allow me to get to the folders i need ?

**Comment by G0UEX** [comment]
Any idea how to access the files when running the full OS in a local VM?

I have tried both via networking and ssh and can not seem to find them.

**Comment by jee67** [comment]
> The hostname is hardcoded in `/usr/local/lib/python3.13/site-packages/evohomeasync2/const.py` and in `/usr/local/lib/python3.13/site-packages/evohomeasync/broker.py` and if I change the hostname from `tccna.honeywell.com` to `tccna.resideo.com` directly in those files in `homeassistant` container and restart homeassistant, the integration works. (As an aside, I was surprised the change survived a container restart, but that's a whole different story)
> 
> I am more than happy to raise this with Resideo customer service myself of course. But someone might find this hacky stopgap useful while Resideo fix their certs.
> 
> (edited to clarify you have to update both evohome-async and evohome-async2 packages)

For me, the files are on a different location. Found them with Linux command "sudo find . -name *evohomeasync*" starting from /

**Comment by cathelijne** [comment]
I should have added I'm running supervised on debian bookworm on a Pi 4...

Anyway, to edit the files inside the container, you have to get inside the container first. Connect to the host running the docker daemon (use what you like: ssh, keyboard+monitor, etc) and on the command prompt, type `docker exec -it homeassistant bash`. This will drop you in a bash session on the container and there you can do your thing.

Remember that after every re-download of the container (which will be _at least_ after every upgrade, but might be sooner than that) you will have to edit the files again. That's why I classify this as a stop-gap and not a real solution.

**Comment by WeberOnline** [comment]
> Any idea how to access the files when running the full OS in a local VM?
> 
> I have tried both via networking and ssh and can not seem to find them.

Here the sames... How to access the files mentioned

**Comment by jee67** [comment]
> > Any idea how to access the files when running the full OS in a local VM?
> > I have tried both via networking and ssh and can not seem to find them.
> 
> Here the sames... How to access the files mentioned

starting from / use `sudo find . -name *evohomeasync*`

**Comment by WeberOnline** [comment]
I'am using HomeAssistant OS 14.0 and HomeAssistant Core 2024.12.02 and also the commando
sudo find . -name *evohomeasync* will not work in SSH

**Comment by cathelijne** [comment]
> I should have added I'm running supervised on debian bookworm on a Pi 4...
> 
> Anyway, to edit the files inside the container, you have to get inside the container first. Connect to the host running the docker daemon (use what you like: ssh, keyboard+monitor, etc) and on the command prompt, type `docker exec -it homeassistant bash`. This will drop you in a bash session on the container and there you can do your thing.
> 
> Remember that after every re-download of the container (which will be _at least_ after every upgrade, but might be sooner than that) you will have to edit the files again. That's why I classify this as a stop-gap and not a real solution.

See this better step by step instructions posten in the github issue over at homeassistant core: https://github.com/home-assistant/core/issues/132366#issuecomment-2539283798

**Comment by johnl** [comment]
changing the hostname in those files fixed it for me too (I'm using home assistant OS and I used the full privilege developer ssh access: https://developers.home-assistant.io/docs/operating-system/debugging/ )

So do we think this is a permanent change now and this library needs updating? Or is resideo going to fix this at their end?

I can't find any mention from resideo about this (other than some planned maintenance that happened today documented on their status page at https://status.resideo.com/ ) but their other apps and devices seem unaffected, so it's quite possible this is permanent.

**Comment by jee67** [comment]
> I'am using HomeAssistant OS 14.0 and HomeAssistant Core 2024.12.02 and also the commando sudo find . -name _evohomeasync_ will not work in SSH

Sorry, I'm on supervised. I now remember why.

**Comment by G0UEX** [comment]
> > > Any idea how to access the files when running the full OS in a local VM?
> > > I have tried both via networking and ssh and can not seem to find them.
> > 
> > 
> > Here the sames... How to access the files mentioned
> 
> starting from / use `sudo find . -name *evohomeasync*`
> 
> You might need `sudo su` to edit the files.

That doesn't work, there is no sudo for starters and trying without finds nothing unfortunately.

**Comment by jee67** [comment]
> > > > Any idea how to access the files when running the full OS in a local VM?
> > > > I have tried both via networking and ssh and can not seem to find them.
> > > 
> > > 
> > > Here the sames... How to access the files mentioned
> > 
> > 
> > starting from / use `sudo find . -name *evohomeasync*`
> > You might need `sudo su` to edit the files.
> 
> That doesn't work, there is no sudo for starters and trying without finds nothing unfortunately.

Sorry, forgot to mention I'm on supervised.

**Comment by G0UEX** [comment]
> > > > > Any idea how to access the files when running the full OS in a local VM?
> > > > > I have tried both via networking and ssh and can not seem to find them.
> > > > 
> > > > 
> > > > Here the sames... How to access the files mentioned
> > > 
> > > 
> > > starting from / use `sudo find . -name *evohomeasync*`
> > > You might need `sudo su` to edit the files.
> > 
> > 
> > That doesn't work, there is no sudo for starters and trying without finds nothing unfortunately.
> 
> Sorry, forgot to mention I'm on supervised.

If that means you are running supervisor then so am I.

**Comment by cathelijne** [comment]
> So do we think this is a permanent change now and this library needs updating? Or is resideo going to fix this at their end?
> 
> I can't find any mention from resideo about this (other than some planned maintenance that happened today documented on their status page at https://status.resideo.com/ ) but their other apps and devices seem unaffected, so it's quite possible this is permanent.

From other issues in this repo it seems that @zxdavb has a good rapport with Resideo tech people. So maybe it's best if there's some clarity about this hostname situation first. Other than that, it might be an idea to add an optional config entry for the API hostname (i.e. use fallback tccna.whichever.domain when apiserver is not set in the config) so we can at least change the apiserver address without meddling in running containers (which makes me shudder... brrrrrrr) and having to do it after every update.

**Comment by G0UEX** [comment]
It's looking like I will have to wait until whoever maintains the integration updates it.

Luckily I decided to leave Domoticz running alongside HA and that is still working fine.

**Comment by jee67** [comment]
> > > > > > Any idea how to access the files when running the full OS in a local VM?
> > > > > > I have tried both via networking and ssh and can not seem to find them.
> > > > > 
> > > > > 
> > > > > Here the sames... How to access the files mentioned
> > > > 
> > > > 
> > > > starting from / use `sudo find . -name *evohomeasync*`
> > > > You might need `sudo su` to edit the files.
> > > 
> > > 
> > > That doesn't work, there is no sudo for starters and trying without finds nothing unfortunately.
> > 
> > 
> > Sorry, forgot to mention I'm on supervised.
> 
> If that means you are running supervisor then so am I.

I mean on Home Assistant Supervised: [https://www.home-assistant.io/installation/](url)

**Comment by IGNWoudenberg** [comment]
Running supervised so not able to edit the files and having the same.

**Comment by G0UEX** [comment]
> > > > > > > Any idea how to access the files when running the full OS in a local VM?
> > > > > > > I have tried both via networking and ssh and can not seem to find them.
> > > > > > 
> > > > > > 
> > > > > > Here the sames... How to access the files mentioned
> > > > > 
> > > > > 
> > > > > starting from / use `sudo find . -name *evohomeasync*`
> > > > > You might need `sudo su` to edit the files.
> > > > 
> > > > 
> > > > That doesn't work, there is no sudo for starters and trying without finds nothing unfortunately.
> > > 
> > > 
> > > Sorry, forgot to mention I'm on supervised.
> > 
> > 
> > If that means you are running supervisor then so am I.
> 
> I mean on Home Assistant Supervised: 'https://www.home-assistant.io/installation/'

I am using the full operating system in a VM.

**Comment by zxdavb** [comment]
Thanks everyone fo your input - I will look at this tonight!

**Comment by cooperised** [comment]
Can confirm that changing the hostnames worked for me (using the library as part of the Home Assistant Evohome integration).  Interestingly the Honeywell app worked when HA did not - if this was just a case of Honeywell messing up the certs I'd have expected the Honeywell app to fail as well.  Does this indicate that the app already uses the tccna.resideo.com endpoints, and that this is part of a permanent migration?

**Comment by PunJum** [comment]
Where can I find these files? I'd like to change the hostnames as well but I'm having difficulties finding the folder in which I can adjust the files. I'm using an Home Assistant installation directly on a NUC. 

I tried using cd .. to move one level up and found the usr folder but there is nothing that relates to Evohome. The whole Evohome integration has been a mystery for me that it just worked by simply putting 'evohome:' in the configuration yaml. It's a pity that such a simple Resideo update messes up my whole smart thermostat here. 

Hopefully I can get this back to work again but I'm going to move to a local method to avoid this in the future...

**Comment by zxdavb** [comment]
Fixed by version 0.4.21, see: **https://github.com/zxdavb/evohome-async/compare/0.4.20...0.4.21**.

Has been published to PyPi - HA fix coming soon.

**Comment by JoepWi** [comment]
> Fixed by version 0.4.21, see: **[0.4.20...0.4.21](https://github.com/zxdavb/evohome-async/compare/0.4.20...0.4.21)**.
> 
> Has been published to PyPi - HA fix coming soon.

Any idea on the timing of having the fix for HA. I'm a unix noob and really do not dare or understand how to edit the files myself. Thanks in advance.

**Comment by thomaswwp** [comment]
I rebooted HA just now and the fix appears to be in, no error and all my zones have reappeared. (FYI HA did not report it needed an update.)

Thank you @zxdavb  👍

**Comment by zxdavb** [comment]
> I rebooted HA just now and the fix appears to be in, no error and all my zones have reappeared. (FYI HA did not report it needed an update.)
> 
> Thank you @zxdavb  👍

If this is true, then it's something that Resideo have done at the server end, because HA 2024.12.3 has not been released yet. 

Or perhaps some of their servers still have the old certificate, (and so it depends which one you're speaking to) which is going to be a disaster!

**Comment by ippo112** [comment]
now, it's work for me, I reboot HA and the integration works fine.
Thanks @zxdavb 👍

**Comment by JoepWi** [comment]
Indeed. Reboot and evohome is 'repaired'.

**Comment by EricJanOud** [comment]
quote
If this is true, then it's something that Resideo have done at the server
end, because HA 2024.12.3 has not been released yet.
/quote

It is true; the Honeywell app also did not work for a number of hours
yesterday. Then, around 17:00 UTC all spontaneously started working there
again. So they did "fix" something at their end. Was just about the same
time as when I managed to get those files edited, so I'm not sure which one
is to "blame" for my successful recovery of the integration ;)

Anyway: thanks for your relentless upkeep of the integration, David!
Cheers!
Eric-Jan Oud

Op vr 13 dec 2024 om 10:10 schreef ippo112 ***@***.***>:

**Comment by checkiecheck** [comment]
Pihole can indeed do the same, good.luck

**Comment by thomaswwp** [comment]
> Pihole can indeed do the same, good.luck

I was interested to learn how to do this and to see if everything works with the different DNS... Irealised it is the same way as I do custom redirects in my home domain so for anyone else with PiHole here is what I did. (I am by no means an expert so if this looks wrong let me know! I imaginge it can be done through the pihole gui too)

- ssh in to your pihole 
- Make a custom .conf in /etc/dnsmasq.d, e.g. /etc/dnsmasq.d/thomaswwp.conf
- Add the below to that conf file and restart pihole

```
# fix for evohome DNS weirdness
address=/tccna.honeywell.com/135.224.164.118
```

BUT - although that seemed to work fine and I could ping tccna.honeywell.com and get 135.224.164.118 on both the HA server and everywhere else on my network - it immediately broke evohome again. When I removed that line it started working again.

**Comment by zxdavb** [comment]
I think there are a few assumptions here that are muddying the water...

The way it works is this:
 a) evohome-in-HA asks of DNS: Where can I speak with tccna.xxx.com?
 - DNS says: call him (or his agent) on this number (IP address)...

 b) evohome-in-HA calls the agent and asks: Are you tccna.xxx.com?
 - that server (_or another server it knows_, the SSL endpoint) says yes/no (by sending evohome in HA a certificate to check - kind of like presenting your passport as proof of ID).

 c) evohome-in-HA says, great: and asks the agent can you do a thing for me...
 - _these_ requests may be handled by a server separate from the previous two (the agent/the endpoint)
 
The failure here is the SSL endpoint (step B). It is quite likely that the two distinct destination IP addresses end up on the same SSL endpoint... Even then, it doesn't matter if they don't, as long as both endpoints says 'yes' (i.e. the hostname on the certificate matches the name in step a).

There's too many factors to know exactly what's going on, but it's fair to say that Resideo could have handled it better.

The fact that tccna.honeywell.com now works is either because:
 1) Resideo saw what is happening and made changes so that that tccna.honeywell.com is now on the certificate passed back to evohome-in-HA
 2) the thing is a mess, and it sometimes works, sometimes doesn't
 
The main problem is 2), because that means tccna.resideo.com may not work 100%, and we won't really know until HA 2023.12.3 is installed by a larger number of users.

**Comment by zxdavb** [comment]
And from what I can see, they've added tccna.honeywell.com back into the certificate. Hopefully, this is the case for all of their SSL endpoints.

**Comment by etvoorde** [comment]
> And from what I can see, they've added tccna.honeywell.com back into the certificate. Hopefully, this is the case for all of their SSL endpoints.

I find the following list in the certificate:

DNS Name: TCCNA.resideo.com
DNS Name: TCCEU.resideo.com
DNS Name: TCCAP.resideo.com
DNS Name: TCCNAS.resideo.com
DNS Name: TCCEUS.resideo.com
DNS Name: TCCAPS.resideo.com
DNS Name: TCCNA.honeywell.com
DNS Name: TCCEU.honeywell.com
DNS Name: TCCAP.honeywell.com
DNS Name: TCCNAS.honeywell.com
DNS Name: TCCEUS.honeywell.com
DNS Name: TCCAPS.honeywell.com

**Comment by freekeys** [comment]
My zones are now showing up in Home Assistant which is great, since the 2024.12.3 fix. But HA doesn’t seem to be able to properly trigger changes to the zones - I keep getting these emails from Honeywell. Anyone else getting the same?

“Dear user,

We would like to notify you that your attempt to remotely implement a change to the following zone failed”

**Comment by uksoftware** [comment]
I`m having the exact same emails. Both yesterday and today.

**Comment by zxdavb** [comment]
> My zones are now showing up in Home Assistant which is great, since the 2024.12.3 fix. But HA doesn’t seem to be able to properly trigger changes to the zones - I keep getting these emails from Honeywell. Anyone else getting the same?
> 
> “Dear user,
> 
> We would like to notify you that your attempt to remotely implement a change to the following zone failed”

Please raise this as a separate issue.

**Comment by checkiecheck** [comment]
HA integration can do anything at my installation. So I wouldn't assume it's HA faulty. Some debug logs would give more info. It just could also be that Honeywell has issues reaching your system

**Comment by kbotty** [comment]
Hi, anuone else still having this issue after the update @zxdavb implemented 2 days ago?
I still get the same error message:

Logger: homeassistant.setup
Bron: setup.py:269
Eerst voorgekomen: 23:43:02 (1 gebeurtenissen)
Laatst gelogd: 23:43:02

Setup failed for 'Evohome': Integration not found.

**Comment by b0ril** [comment]
I had to go back to tccna.honeywell.com from tccna.resideo.com since I got error today:
Failed to authenticate with the vendor's server. Check your username and password. NB: Some special password characters that work correctly via the website will not work via the web API. Message is: 502, message='Bad Gateway', url='https://tccna.resideo.com/Auth/OAuth/Token'

**Comment by zxdavb** [comment]
> I had to go back to tccna.honeywell.com from tccna.resideo.com since I got error today:
```
Failed to authenticate with the vendor's server. Check your username and password. NB: Some special password characters that work correctly via the website will not work via the web API. Message is: 502, message='Bad Gateway', url='https://tccna.resideo.com/Auth/OAuth/Token'
```

Your solution may have 'solved' your problem, but see here: https://github.com/home-assistant/core/issues/138473

**Comment by zxdavb** [comment]
All, please do not post on closed issues. Instead raise a new issue, and refer to the closed issue.
