### ISSUE TITLE
Home Assistant custom repo error

### ISSUE THREAD

**Issue by ulicskad** [zxdavb/evohome-async#5]
Hi!
First of all I am new to HA, so forgive me if this question is dumb.

HA says "Repostitory structure for master is not compliant" when I want to add as a custom repo in HACS. 
I copy link (https://github.com/zxdavb/evohome-async), set "integration" and this message appears. Any recommendations?
TIA,
David

**Comment by zxdavb** [comment]
This is the wrong repo, I think you want to use: https://github.com/zxdavb/evohome_cc

Please ask these sort of questions at this forum (it will be more helpful to you to do so): https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/1119

**Comment by ulicskad** [comment]
Hi zxdavb,

Thanks for your answer. I have read this article: https://www.home-assistant.io/integrations/evohome/
I have got 2pcs BDR91 and 2pcs T86RF +gateway connected to Honeywell Total Connect Comfort international. I would like to use my account to sync data with HA. Evohome_cc integration with HA is working, but I think this is not what i am looking for. I don't have and want any serial device, just connect the backend. As I read, it should be possible with evohome_async library. And as I see in older forum posts, this lib works well. Did I do something wrong?

Thanks.

**Comment by zxdavb** [comment]
https://www.home-assistant.io/integrations/evohome/ is an official integration - you don't use HACS for it. 
- for support, ask here: https://community.home-assistant.io/t/official-honeywell-evohome-round-thermostat-integration-eu-only/59733

**Comment by ulicskad** [comment]
Hi,

I am sorry for misunderstand! Works without HACS perfectly. Thank you for your help!
