### ISSUE TITLE
Home Assistant: Multiple Evohome Locations WIKI not working

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [zxdavb/evohome-async#9]
@zxdavb 

I followed all the steps in the "Home Assistant: Multiple Evohome Locations" WIKI you posted but still I not am able to add a secondary integration of evohome, if I go to "Developer Tools > Check Configuration" I still receive the following error message  

`"integration error: ‘evohome_1’ - not found.`

it is the same error as before when i tryed to add integration to my /config/custom_components through "file editor" and  "samba share add-on" (copy and create using windows PC)

**Comment by zxdavb** [comment]
resolved

**Comment by rosariourzi** [comment]
> "integration error: ‘evohome_1’ - not found.

how didi you solve it ? I'm using HA core, Thanks

**Comment by smarthomefamilyverrips** [comment]
> > "integration error: ‘evohome_1’ - not found.
> 
> how didi you solve it ? I'm using HA core, Thanks

@rosariourzi in the link you csn find what I did do to make it work

https://community.home-assistant.io/t/workaround-evohome-multiple-concurrent-locations/161353/37?page=3
